### ISSUE TITLE
Issues in loading checkpoint

### ISSUE THREAD

**Issue by YoihenBachu** [mahmoodlab/SISH#3]
When running the build_index.py using the reproducibility checkpoints, I got this error

Traceback (most recent call last):
  File "/content/SISH/build_index.py", line 286, in <module>
    vqvae_weight_value = torch.load(args.checkpoint)['model']
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: storage has wrong byte size: expected %ld got %ld-7214483042584977081024

**Comment by ChenChengKuan** [comment]
Could your provide your pytorch version? it seems to be a pytorch version error as I didn't see this message before

**Comment by YoihenBachu** [comment]
Name: torch
Version: 2.0.0+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: [packages@pytorch.org](mailto:packages@pytorch.org)
License: BSD-3
Location: /usr/local/lib/python3.9/dist-packages
Requires: filelock, jinja2, networkx, sympy, triton, typing-extensions
Required-by: fastai, torchaudio, torchdata, torchtext, torchvision, triton

**Comment by YoihenBachu** [comment]
I have downgraded the pytorch version from 2.0 to 1.13.1 and it's still giving the same error.

Traceback (most recent call last):
  File "/content/SISH/build_index.py", line 286, in <module>
    vqvae_weight_value = torch.load(args.checkpoint)['model']
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 1754133 more bytes. The file might be corrupted.

**Comment by ChenChengKuan** [comment]
Not sure about your all environment in your system, it appears to be pytorch version issue not the codebase. I would recommend to follow the installation guide in the README.md to get the repo work. Thanks
